import type { TeacherRecord } from './types'

// Seed teachers list
export const SEED_TEACHERS: TeacherRecord[] = [
  {
    id: 'T-001',
    employeeId: 'EMP-001',
    teacherId: 'TCH-2025-001',
    name: 'Dr. Ananya Iyer',
    avatar: 'AI',
    gender: 'Female',
    dob: '1980-04-12',
    bloodGroup: 'O+',
    aadhaarNo: '9845 2019 3847',
    nationality: 'Indian',
    religion: 'Hindu',
    category: 'General',
    email: 'ananya.iyer@greenwood.edu.in',
    phone: '+91 98100 11223',
    emergencyContact: { name: 'Srinivasan Iyer', relation: 'Spouse', phone: '+91 98100 99887' },
    currentAddress: 'DLF Phase 3, Gurugram, Haryana',
    permAddress: 'DLF Phase 3, Gurugram, Haryana',
    sameAddress: true,
    district: 'Gurugram',
    state: 'Haryana',
    pincode: '122002',
    educationalQualifications: [
      { degree: 'Ph.D. Physics', specialization: 'Quantum Optics', institution: 'IIT Delhi', year: '2005', score: 'Doctorate' },
      { degree: 'M.Sc. Physics', specialization: 'Pure Physics', institution: 'Delhi University', year: '2001', score: '84.5%' },
    ],
    professionalQualifications: ['B.Ed (Gold Medalist)', 'M.Ed'],
    totalExperience: 24,
    keyAchievements: 'Published 8 research papers. Recipient of State Best Educator Award 2021.',
    previousEmployment: { organization: 'Modern School, Barakhamba Road', designation: 'Vice Principal', lastSalary: 150000, duration: '2010–2020' },
    joiningDate: '2001-06-15',
    employmentType: 'Full Time',
    department: 'Administration',
    designation: 'Principal',
    status: 'Active',
    attendance: 98,
    salary: 185000,
    salaryBreakdown: { basic: 92500, hra: 37000, da: 27750, specialAllowance: 18500, pfDeduction: 9250, netPay: 166500 },
    bankDetails: { bankName: 'HDFC Bank', accountNo: '50100293847102', ifscCode: 'HDFC0000240', branchName: 'DLF Phase 3' },
    subjects: ['Physics'],
    classes: [],
    examResponsibilities: ['Chief Controller of Examinations'],
    positions: [
      { id: 'pa-101', positionId: 'pos-vice-principal', positionTitle: 'Vice Principal', assignedDate: '2021-06-01', assignedBy: 'Board of Governors', status: 'Active', effectiveDate: '2021-06-01' },
    ],
    documents: [
      { id: 'doc-1', title: 'Ph.D Degree Certificate', category: 'Qualification', fileName: 'Phd_Degree_Ananya.pdf', uploadDate: '2021-06-15', status: 'Verified' },
      { id: 'doc-2', title: 'Aadhaar Card', category: 'ID Proof', fileName: 'Aadhaar_Ananya.pdf', uploadDate: '2021-06-15', status: 'Verified' },
    ],
    appointmentLetter: {
      id: 'APT-GWS-2021-001',
      officialLetterNo: "GWS/APT/2021/0001",
      generatedDate: '2001-06-10',
      teacherName: 'Dr. Ananya Iyer',
      employeeId: 'EMP-001',
      designation: 'Principal',
      department: 'Administration',
      joiningDate: '2001-06-15',
      monthlySalary: 185000,
      annualSalary: 2220000,
      workingHours: '08:00 AM – 04:00 PM',
      probationMonths: 6,
      noticePeriodDays: 90,
      termsAndConditions: [
        'Adherence to CBSE Code of Professional Ethics for School Principals.',
        'Full administrative authority over academic schedules, faculty evaluations, and student affairs.',
        'Confidentiality regarding institutional finances and board proceedings.',
      ],
      qrVerificationId: 'QR-APT-EMP-001-2021A1B2C3',
      reportingAuthority: 'Board of Governors',
      principalName: 'Chairman, Board of Governors',
      schoolSealAttached: true,
    },
    loginCredentials: { username: 'principal.ananya@greenwood.edu.in', tempPassword: 'GWS#Principal2025', passwordResetRequired: false, createdDate: '2021-06-15' },
  },
  {
    id: 'T-014',
    employeeId: 'EMP-014',
    teacherId: 'TCH-2025-014',
    name: 'Rohan Mehta',
    avatar: 'RM',
    gender: 'Male',
    dob: '1988-09-22',
    bloodGroup: 'A+',
    aadhaarNo: '4829 1029 3847',
    nationality: 'Indian',
    religion: 'Hindu',
    category: 'General',
    email: 'rohan.mehta@greenwood.edu.in',
    phone: '+91 98600 44556',
    emergencyContact: { name: 'Kavita Mehta', relation: 'Spouse', phone: '+91 98600 11223' },
    currentAddress: 'Sector 40, Gurugram, Haryana',
    permAddress: 'Sector 40, Gurugram, Haryana',
    sameAddress: true,
    district: 'Gurugram',
    state: 'Haryana',
    pincode: '122001',
    educationalQualifications: [
      { degree: 'M.Sc. Mathematics', specialization: 'Applied Math', institution: 'DU', year: '2010', score: '78.2%' },
      { degree: 'B.Sc. Mathematics', specialization: 'Mathematics', institution: 'Hansraj College', year: '2008', score: '81.0%' },
    ],
    professionalQualifications: ['B.Ed', 'CTET Paper II Cleared'],
    totalExperience: 9,
    keyAchievements: 'Coached National Math Olympiad winners in 2022.',
    previousEmployment: { organization: 'DPS Sushant Lok', designation: 'Mathematics Teacher', lastSalary: 52000, duration: '2012–2015' },
    joiningDate: '2015-06-01',
    employmentType: 'Full Time',
    department: 'Mathematics',
    designation: 'Senior Teacher',
    status: 'Active',
    attendance: 98,
    salary: 64000,
    salaryBreakdown: { basic: 32000, hra: 12800, da: 9600, specialAllowance: 6400, pfDeduction: 3200, netPay: 57600 },
    bankDetails: { bankName: 'ICICI Bank', accountNo: '002101589342', ifscCode: 'ICIC0000021', branchName: 'Sector 31' },
    subjects: ['Mathematics', 'Computer Science'],
    classes: ['Class 2-A', 'Class 2-B', 'Class 2-C'],
    examResponsibilities: ['Invigilator Math Mid-term'],
    positions: [
      { id: 'pa-102', positionId: 'pos-subject-teacher', positionTitle: 'Subject Teacher', assignedDate: '2015-06-01', assignedBy: 'Dr. Ananya Iyer', status: 'Active', effectiveDate: '2015-06-01' },
      { id: 'pa-103', positionId: 'pos-class-teacher', positionTitle: 'Class Teacher', assignedDate: '2023-04-01', assignedBy: 'Dr. Ananya Iyer', status: 'Active', effectiveDate: '2023-04-01' },
      { id: 'pa-104', positionId: 'pos-timetable-coordinator', positionTitle: 'Time Table Coordinator', assignedDate: '2025-07-20', assignedBy: 'Dr. Ananya Iyer', status: 'Pending Acceptance', effectiveDate: '2025-08-01' },
    ],
    documents: [
      { id: 'doc-10', title: 'M.Sc Degree Certificate', category: 'Qualification', fileName: 'MSc_Math_Rohan.pdf', uploadDate: '2015-06-01', status: 'Verified' },
      { id: 'doc-11', title: 'B.Ed Certificate', category: 'Qualification', fileName: 'BEd_Rohan.pdf', uploadDate: '2015-06-01', status: 'Verified' },
    ],
    appointmentLetter: {
      id: 'APT-GWS-2015-014',
      officialLetterNo: "GWS/APT/2015/0014",
      generatedDate: '2015-05-25',
      teacherName: 'Rohan Mehta',
      employeeId: 'EMP-014',
      designation: 'Senior Teacher',
      department: 'Mathematics',
      joiningDate: '2015-06-01',
      monthlySalary: 64000,
      annualSalary: 768000,
      workingHours: '08:00 AM – 03:30 PM',
      probationMonths: 12,
      noticePeriodDays: 60,
      termsAndConditions: [
        'Adherence to CBSE curriculum guidelines and lesson planning standards.',
        'Active participation in house activities and invigilation duties.',
        'Continuous professional development and workshop attendance.',
      ],
      principalName: 'Dr. Ananya Iyer',
      qrVerificationId: 'QR-APT-EMP-014-2015D4E5F6',
      reportingAuthority: 'Dr. Ananya Iyer, Principal',
      schoolSealAttached: true,
    },
    loginCredentials: { username: 'rohan.mehta@greenwood.edu.in', tempPassword: 'GWS#Teacher2025', passwordResetRequired: false, createdDate: '2015-06-01' },
  },
]

// Initial audit log entries seeded into the store on first load.
export const INITIAL_AUDIT_LOGS = [
  {
    id: 'log-1',
    timestamp: '2025-07-20T10:30:00Z',
    category: 'Teacher Created' as const,
    actorName: 'Dr. Ananya Iyer',
    actorRole: 'Principal',
    targetTeacherId: 'T-014',
    targetTeacherName: 'Rohan Mehta',
    details: 'Registered Rohan Mehta as Senior Teacher (Mathematics)',
  },
  {
    id: 'log-2',
    timestamp: '2025-07-20T11:15:00Z',
    category: 'Position Assigned' as const,
    actorName: 'Dr. Ananya Iyer',
    actorRole: 'Principal',
    targetTeacherId: 'T-014',
    targetTeacherName: 'Rohan Mehta',
    details: 'Assigned position: Time Table Coordinator (Pending Teacher Acceptance)',
  },
]
