/**
 * Schedule PDF — compact printable examination timetable.
 *
 * Spec: generates a clean PDF from the CURRENT schedule state (not a stale
 * template). Reflects any drag/date/time/room/invigilator edits.
 */

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { ExamDTO } from '@/lib/exams/types'
import { formatDateLong } from '@/lib/exams/format-helpers'

export function generateSchedulePDF(exam: ExamDTO): void {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()

  // Header — centered
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Demo School of Scholario', pageW / 2, 14, { align: 'center' })
  doc.setFontSize(11)
  doc.text(exam.name, pageW / 2, 20, { align: 'center' })
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  const meta = `Academic Session ${exam.session} · ${exam.startDate ? formatDateLong(exam.startDate) : ''} – ${exam.endDate ? formatDateLong(exam.endDate) : ''}`
  doc.text(meta, pageW / 2, 25, { align: 'center' })
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.text('EXAMINATION TIMETABLE', pageW / 2, 30, { align: 'center' })

  // Group schedule by date
  const byDate = new Map<string, typeof exam.schedule>()
  for (const item of exam.schedule) {
    if (!byDate.has(item.date)) byDate.set(item.date, [])
    byDate.get(item.date)!.push(item)
  }

  // Build table rows: Date | Time | Class | Subject | Room | Invigilator
  const rows: string[][] = []
  const sortedDates = Array.from(byDate.keys()).sort()
  for (const date of sortedDates) {
    const items = byDate.get(date)!
    items.sort((a, b) => a.startTime.localeCompare(b.startTime))
    for (const item of items) {
      const cls = exam.classes.find((c) => c.classId === item.classId)
      rows.push([
        formatDateLong(date),
        `${item.startTime} – ${item.endTime}`,
        cls?.className ?? item.classId,
        item.subjectName ?? '—',
        item.room ?? '—',
        item.invigilatorName ?? '—',
      ])
    }
  }

  autoTable(doc, {
    head: [['Date', 'Time', 'Class', 'Subject', 'Room', 'Invigilator']],
    body: rows,
    startY: 35,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [15, 118, 110], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 250, 249] },
  })

  // Footer
  const pageH = doc.internal.pageSize.getHeight()
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.text('Official examination timetable — generated by Scholario-OS', pageW / 2, pageH - 5, { align: 'center' })

  doc.save(`${exam.name.replace(/\s+/g, '-')}-schedule.pdf`)
}
