/**
 * Schedule PDF — landscape printable examination timetable grid.
 *
 * Spec: the PDF must look like the visual timetable preview (date rows ×
 * class columns), NOT a flat database export. No room, no invigilator.
 */

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { ExamDTO } from '@/lib/exams/types'
import type { ConsolidatedTimetable } from '@/lib/exams/schedule/consolidate'
import { formatDateLong } from '@/lib/exams/format-helpers'

export function generateSchedulePDF(exam: ExamDTO, timetable?: ConsolidatedTimetable): void {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()

  // Header — centered
  doc.setFontSize(14); doc.setFont('helvetica', 'bold')
  doc.text('Demo School of Scholario', pageW / 2, 14, { align: 'center' })
  doc.setFontSize(11)
  doc.text(exam.name, pageW / 2, 20, { align: 'center' })
  doc.setFontSize(9); doc.setFont('helvetica', 'normal')
  const dateRange = exam.startDate && exam.endDate
    ? `${formatDateLong(exam.startDate)} – ${formatDateLong(exam.endDate)}`
    : ''
  doc.text(`Academic Session ${exam.session ?? ''}  ·  ${dateRange}`, pageW / 2, 25, { align: 'center' })
  doc.setFontSize(8); doc.setFont('helvetica', 'bold')
  doc.text('EXAMINATION TIMETABLE', pageW / 2, 30, { align: 'center' })

  // Build table: one row per (date × slot). Columns: Day/Date | class1 | class2 | ...
  const columns = timetable?.columns ?? []
  const head = [['Day / Date', ...columns.map((c) => c.label)]]

  const body: string[][] = []
  if (timetable) {
    // Group rows by date
    const byDate = new Map<string, typeof timetable.rows>()
    for (const row of timetable.rows) {
      if (!byDate.has(row.date)) byDate.set(row.date, [])
      byDate.get(row.date)!.push(row)
    }
    for (const [date, rows] of byDate) {
      const dateLabel = formatDateLong(date)
      const dayLabel = rows[0]?.dayLabel ?? ''
      for (const row of rows) {
        const cells = columns.map((col, colIdx) => {
          const cell = row.cells[colIdx]
          if (!cell) return '—'
          return `${cell.label}\n${row.startTime}–${row.endTime}`
        })
        body.push([`${dayLabel}\n${dateLabel}`, ...cells])
      }
    }
  }

  autoTable(doc, {
    head,
    body,
    startY: 35,
    styles: { fontSize: 7, cellPadding: 1.5, valign: 'middle', overflow: 'linebreak' },
    headStyles: { fillColor: [15, 118, 110], textColor: 255, fontSize: 7 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 25 } },
    alternateRowStyles: { fillColor: [245, 250, 249] },
    didParseCell: (data) => {
      if (data.column.index === 0) {
        data.cell.styles.fontStyle = 'bold'
      }
    },
  })

  // Footer
  const pageH = doc.internal.pageSize.getHeight()
  doc.setFontSize(7); doc.setFont('helvetica', 'normal')
  doc.text('Official examination timetable — generated by Scholario-OS', pageW / 2, pageH - 5, { align: 'center' })

  doc.save(`${exam.name.replace(/\s+/g, '-')}-schedule.pdf`)
}
