/**
 * Seating plan PDF — landscape, room-by-room with bench layout + invigilators.
 */

import { jsPDF } from 'jspdf'
import type { ExamDTO } from '@/lib/exams/types'
import type { SeatingPlan, ExamSlot, InvigilationAssignment } from '@/lib/exams/seating/types'
import { seatsForRoom, roomOccupancy } from '@/lib/exams/seating/generator'
import { formatDateLong } from '@/lib/exams/format-helpers'

export function generateSeatingPlanPDF(
  exam: ExamDTO,
  plan: SeatingPlan,
  examSlots: ExamSlot[] = [],
  invigilators: InvigilationAssignment[] = [],
): void {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()

  // Global header
  doc.setFontSize(14); doc.setFont('helvetica', 'bold')
  doc.text('Demo School of Scholario', pageW / 2, 14, { align: 'center' })
  doc.setFontSize(11)
  doc.text(exam.name, pageW / 2, 20, { align: 'center' })
  doc.setFontSize(9); doc.setFont('helvetica', 'normal')
  doc.text(`Academic Session ${exam.session ?? ''}`, pageW / 2, 25, { align: 'center' })
  doc.setFontSize(8); doc.setFont('helvetica', 'bold')
  doc.text('SEATING PLAN', pageW / 2, 30, { align: 'center' })

  let y = 38
  for (const room of plan.rooms) {
    const { occupied, capacity } = roomOccupancy(plan, room.id)
    const seats = seatsForRoom(plan, room.id)
    const posCount = room.seatingType === 'triple' ? 3 : room.seatingType === 'double' ? 2 : 1

    // Room header
    doc.setFontSize(10); doc.setFont('helvetica', 'bold')
    doc.text(`${room.name} — ${room.roomNo}`, 14, y)
    doc.setFontSize(7); doc.setFont('helvetica', 'normal')
    doc.text(`${room.rows}×${room.cols} · ${room.seatingType} · ${occupied}/${capacity} occupied`, 14, y + 4)

    // Invigilator info for first slot (if available)
    const firstSlot = examSlots[0]
    if (firstSlot) {
      const roomInvs = invigilators.filter((a) => a.roomId === room.id && a.examSlotId === firstSlot.id)
      if (roomInvs.length > 0) {
        doc.text(`Invigilators (${firstSlot.shiftLabel}): ${roomInvs.map((i) => i.teacherName).join(', ')}`, 14, y + 7)
      }
    }

    // Invigilator desk marker
    doc.setFontSize(6); doc.setFont('helvetica', 'bold')
    doc.text('INVIGILATOR DESK', pageW / 2, y + 2, { align: 'center' })
    y += 10

    // Column numbers
    const benchW = Math.min(30, (pageW - 40) / room.cols)
    const gridStartX = (pageW - room.cols * benchW) / 2
    doc.setFontSize(5); doc.setFont('helvetica', 'normal')
    for (let c = 0; c < room.cols; c++) {
      doc.text(String(c + 1), gridStartX + c * benchW + benchW / 2, y, { align: 'center' })
    }
    y += 3

    // Rows with benches
    const seatH = posCount > 1 ? 12 : 8
    for (let r = 0; r < room.rows; r++) {
      const ry = y + r * (seatH + 3)

      // Row label
      doc.setFontSize(5); doc.setFont('helvetica', 'bold')
      doc.text(String.fromCharCode(65 + r), gridStartX - 4, ry + seatH / 2)

      for (let c = 0; c < room.cols; c++) {
        const cellSeats = seats.filter((s) => s.rowIdx === r && s.colIdx === c)
          .sort((a, b) => (a.position ?? '').localeCompare(b.position ?? ''))
        const cx = gridStartX + c * benchW

        if (cellSeats.length === 0) continue

        // Draw bench border
        doc.setDrawColor(180)
        doc.setFillColor(250, 250, 250)
        doc.rect(cx, ry, benchW - 1, seatH, 'FD')

        // Draw position dividers + student info
        const posW = (benchW - 1) / cellSeats.length
        for (let si = 0; si < cellSeats.length; si++) {
          const seat = cellSeats[si]
          const px = cx + si * posW

          if (si > 0) {
            doc.setDrawColor(200)
            doc.line(px, ry, px, ry + seatH)
          }

          if (seat.studentId) {
            doc.setFillColor(240, 250, 245)
            doc.rect(px + 0.5, ry + 0.5, posW - 1, seatH - 1, 'F')

            doc.setFontSize(5); doc.setFont('helvetica', 'bold')
            doc.setTextColor(30, 30, 30)
            const name = seat.studentName ?? ''
            doc.text(name.length > 10 ? name.substring(0, 10) : name, px + 1, ry + 4)

            doc.setFontSize(4); doc.setFont('helvetica', 'normal')
            doc.setTextColor(80, 80, 80)
            doc.text(`Roll ${seat.studentRollNo ?? ''}`, px + 1, ry + 6.5)

            doc.setTextColor(15, 100, 80)
            doc.text(seat.className ?? '', px + 1, ry + 8.5)
          } else {
            doc.setFontSize(4); doc.setTextColor(180, 180, 180)
            doc.text('Empty', px + 1, ry + seatH / 2)
          }
          doc.setTextColor(0, 0, 0)
        }
      }
    }
    y += room.rows * (seatH + 3) + 8
    if (y > pageH - 20) { doc.addPage(); y = 14 }
  }

  // Footer
  doc.setFontSize(6); doc.setFont('helvetica', 'normal')
  doc.text('Official seating plan — generated by Scholario-OS', pageW / 2, pageH - 4, { align: 'center' })

  doc.save(`${exam.name.replace(/\s+/g, '-')}-seating-plan.pdf`)
}
