'use client'

/**
 * document-list — the document table/list.
 *
 * Refined library-style table with subtle row hover, small file-type icons,
 * source + format badges, and per-row Preview / Download / More actions.
 *
 * Click anywhere on the row (outside the actions) opens the detail drawer.
 */

import { useMemo } from 'react'
import { motion } from 'framer-motion'
import {
  Eye, Download, MoreHorizontal, FileCheck2, Search, X,
  RotateCcw, Printer, Share2, Star, Info,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu, DropdownMenuTrigger, DropdownMenuContent,
  DropdownMenuItem, DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu'
import { toast } from 'sonner'
import { formatDate, formatRelativeTime } from '@/lib/format'
import {
  useDownloadsStore,
  type DownloadDocument,
} from '@/lib/store/downloads-store'
import {
  SourceBadge, CategoryPill,
  DownloadsEmptyState, docDescriptionLabel,
} from './downloads-shared'
import {
  DocumentThumbnail, FileTypeBadge,
} from '@/components/shared/document-primitives'
import type { DocFormat } from '@/components/shared/document-primitives'

interface DocumentListProps {
  onSelectDoc: (doc: DownloadDocument) => void
}

export function DocumentList({ onSelectDoc }: DocumentListProps) {
  const getFilteredDocuments = useDownloadsStore((s) => s.getFilteredDocuments)
  const download = useDownloadsStore((s) => s.download)
  const recordPreview = useDownloadsStore((s) => s.recordPreview)
  const resetFilters = useDownloadsStore((s) => s.resetFilters)
  const query = useDownloadsStore((s) => s.query)
  const categoryFilter = useDownloadsStore((s) => s.categoryFilter)
  const categoryTab = useDownloadsStore((s) => s.categoryTab)
  const sortBy = useDownloadsStore((s) => s.sortBy)

  const docs = useMemo(
    () => getFilteredDocuments(),
    [getFilteredDocuments, query, categoryFilter, categoryTab, sortBy],
  )

  function handleDownload(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    const filename = download(doc)
    toast.success('Download started', {
      description: `${filename} · ${doc.format}`,
    })
  }

  function handlePreview(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    recordPreview(doc)
    onSelectDoc(doc)
  }

  function handlePrint(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    if (doc.docNumber) {
      toast.info('Opening print view…', { description: doc.docNumber })
    } else {
      toast.info('Opening print view…', { description: doc.name })
    }
    // Surface a printable stub via the detail drawer for generated docs
    onSelectDoc(doc)
  }

  function handleShare(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    toast.success('Link copied', { description: `${doc.name} share link ready` })
  }

  function handlePin(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    toast.success('Added to favourites', { description: doc.name })
  }

  function handleRegenerate(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    toast.info('Regenerating document…', { description: doc.docNumber ?? doc.name })
  }

  if (docs.length === 0) {
    const filtered = (query.trim().length > 0) || (categoryFilter !== 'All') || (categoryTab !== 'All')
    return (
      <DownloadsEmptyState
        icon={filtered ? <Search className="h-5 w-5" /> : <FileCheck2 className="h-5 w-5" />}
        title={filtered ? 'No documents match the filters' : 'No documents yet'}
        description={
          filtered
            ? 'Try a different search term, clear the category filter, or switch tabs.'
            : 'Documents generated by the system will appear here automatically.'
        }
        action={
          filtered ? (
            <Button variant="outline" size="sm" onClick={resetFilters} className="h-8 text-xs gap-1.5">
              <X className="h-3.5 w-3.5" /> Clear filters
            </Button>
          ) : undefined
        }
      />
    )
  }

  return (
    <div className="rounded-xl border border-border bg-card overflow-hidden">
      {/* Table — overflow-x-auto for small screens */}
      <div className="overflow-x-auto downloads-list-scroll">
        <table className="w-full text-xs min-w-[720px]">
          <thead>
            <tr className="border-b border-border bg-muted/30 text-[10px] uppercase tracking-wider text-muted-foreground">
              <th className="text-left font-semibold px-3 py-2.5 w-[44%]">Document</th>
              <th className="text-left font-semibold px-3 py-2.5">Category</th>
              <th className="text-left font-semibold px-3 py-2.5">Source</th>
              <th className="text-left font-semibold px-3 py-2.5">Format</th>
              <th className="text-left font-semibold px-3 py-2.5 whitespace-nowrap">Updated</th>
              <th className="text-right font-semibold px-3 py-2.5">Actions</th>
            </tr>
          </thead>
          <tbody>
            {docs.map((doc, i) => {
              const isGenerated = doc.source === 'Generated'
              return (
                <motion.tr
                  key={doc.id}
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.18, delay: Math.min(i * 0.012, 0.18) }}
                  onClick={() => onSelectDoc(doc)}
                  className={cn(
                    'group border-b border-border/40 last:border-b-0 cursor-pointer transition-colors',
                    'hover:bg-emerald-50/40 dark:hover:bg-emerald-500/[0.04]',
                  )}
                >
                  {/* Document cell — DocumentThumbnail (paper silhouette +
                      format edge stripe) + name + description. Reads like
                      a real document, not an icon tile. */}
                  <td className="px-3 py-2.5">
                    <div className="flex items-center gap-2.5 min-w-0">
                      <DocumentThumbnail format={doc.format as DocFormat} size="sm" />
                      <div className="min-w-0 flex-1">
                        <p className="font-semibold text-foreground leading-tight truncate">
                          {doc.name}
                        </p>
                        <p className="text-[10px] text-muted-foreground truncate mt-0.5">
                          {docDescriptionLabel(doc)}
                          {doc.size && (
                            <>
                              <span className="text-muted-foreground/40 mx-1">·</span>
                              <span className="tabular-nums">{doc.size}</span>
                            </>
                          )}
                        </p>
                      </div>
                    </div>
                  </td>

                  {/* Category */}
                  <td className="px-3 py-2.5">
                    <CategoryPill category={doc.category} />
                  </td>

                  {/* Source */}
                  <td className="px-3 py-2.5">
                    <SourceBadge source={doc.source} />
                  </td>

                  {/* Format — FileTypeBadge from shared primitives */}
                  <td className="px-3 py-2.5">
                    <FileTypeBadge format={doc.format as DocFormat} />
                  </td>

                  {/* Updated date */}
                  <td className="px-3 py-2.5 text-[10px] text-muted-foreground whitespace-nowrap">
                    <span className="block font-medium text-foreground/80">
                      {formatRelativeTime(doc.updatedDate)}
                    </span>
                    <span className="block text-[9px] text-muted-foreground/70 tabular-nums">
                      {formatDate(doc.updatedDate)}
                    </span>
                  </td>

                  {/* Actions */}
                  <td className="px-3 py-2.5">
                    <div className="flex items-center justify-end gap-0.5">
                      <Button
                        variant="ghost" size="sm"
                        className="h-7 w-7 p-0 text-muted-foreground hover:text-foreground"
                        onClick={(e) => handlePreview(doc, e)}
                        title="Preview"
                        aria-label={`Preview ${doc.name}`}
                      >
                        <Eye className="h-3.5 w-3.5" />
                      </Button>
                      <Button
                        variant="ghost" size="sm"
                        className="h-7 w-7 p-0 text-muted-foreground hover:text-emerald-600 dark:hover:text-emerald-400"
                        onClick={(e) => handleDownload(doc, e)}
                        title="Download"
                        aria-label={`Download ${doc.name}`}
                      >
                        <Download className="h-3.5 w-3.5" />
                      </Button>
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button
                            variant="ghost" size="sm"
                            className="h-7 w-7 p-0 text-muted-foreground hover:text-foreground"
                            onClick={(e) => e.stopPropagation()}
                            title="More actions"
                            aria-label={`More actions for ${doc.name}`}
                          >
                            <MoreHorizontal className="h-3.5 w-3.5" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end" className="w-44 text-xs">
                          <DropdownMenuItem onClick={(e) => { e.stopPropagation(); handlePreview(doc) }}>
                            <Eye className="h-3.5 w-3.5 mr-1.5" /> Preview
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={(e) => { e.stopPropagation(); handleDownload(doc) }}>
                            <Download className="h-3.5 w-3.5 mr-1.5" /> Download
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={(e) => { e.stopPropagation(); handlePrint(doc) }}>
                            <Printer className="h-3.5 w-3.5 mr-1.5" /> Print
                          </DropdownMenuItem>
                          <DropdownMenuSeparator />
                          <DropdownMenuItem onClick={(e) => { e.stopPropagation(); handleShare(doc) }}>
                            <Share2 className="h-3.5 w-3.5 mr-1.5" /> Copy share link
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={(e) => { e.stopPropagation(); handlePin(doc) }}>
                            <Star className="h-3.5 w-3.5 mr-1.5" /> Add to favourites
                          </DropdownMenuItem>
                          {isGenerated && doc.docNumber && (
                            <>
                              <DropdownMenuSeparator />
                              <DropdownMenuItem onClick={(e) => { e.stopPropagation(); handleRegenerate(doc) }}>
                                <RotateCcw className="h-3.5 w-3.5 mr-1.5" /> Regenerate
                              </DropdownMenuItem>
                              <DropdownMenuItem onClick={(e) => { e.stopPropagation(); onSelectDoc(doc) }}>
                                <Info className="h-3.5 w-3.5 mr-1.5" /> View record
                              </DropdownMenuItem>
                            </>
                          )}
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </div>
                  </td>
                </motion.tr>
              )
            })}
          </tbody>
        </table>
      </div>

      {/* Footer summary line */}
      <div className="flex items-center justify-between px-3 py-2 border-t border-border/60 bg-muted/20 text-[10px] text-muted-foreground">
        <span>
          Showing <strong className="text-foreground tabular-nums">{docs.length}</strong>{' '}
          {docs.length === 1 ? 'document' : 'documents'}
        </span>
        <span className="hidden sm:inline-flex items-center gap-1.5">
          <span className="tabular-nums">{docs.filter((d) => d.source === 'Generated').length}</span> generated
          <span className="text-muted-foreground/40">·</span>
          <span className="tabular-nums">{docs.filter((d) => d.source === 'Official Form').length}</span> forms
          <span className="text-muted-foreground/40">·</span>
          <span className="tabular-nums">{docs.filter((d) => d.source === 'Template').length}</span> templates
        </span>
      </div>
    </div>
  )
}
